# Простейший тест бота линтом, позже также добавлю тесты pytest

name: Run Tests

on: [ push, pull_request, release ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install -Ur tests_requirements.txt
    - name: Lint with flake8
      run: |
        # крашит билд если есть ошибки синтаксиса или не обьявленные переменные
        flake8 . --exclude .*,__*__,venv --count --select=E9,F63,F7,F82 --show-source
        # exit-zero переводит все ошибки в предупреждения. Редактор GitHub 127 символов в ширину
        flake8 . --exclude .*,__*__,venv --count --exit-zero --max-complexity=10 --max-line-length=127 --ignore=E70
  deploy:
    needs: test
    if: |
      needs.test.result == 'success' &&
      github.event_name != 'pull_request'
      

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.ftp_server }}
        ftp-username: ${{ secrets.ftp_username }}
        ftp-password: ${{ secrets.ftp_password }}
        git-ftp-args: --insecure
