# Автоматический деплой бота в хостинг
# Устаревшая версия, потому что последняя не поддерживает SFTP

name: FTP Deploy

on:
  workflow_run:
    workflows: Run Tests
    branches: main
    types: 
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 # pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # крашит билд если есть ошибки синтаксиса или не обьявленные переменные
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero переводит все ошибки в предупреждения. Редактор GitHub 127 символов в ширину
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Test with pytest
    #  run: pytest
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.ftp_server }}
        ftp-username: ${{ secrets.ftp_username }}
        ftp-password: ${{ secrets.ftp_password }}
        git-ftp-args: --insecure
